name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to ghcr.io
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Lowercase repository name & get commit SHA
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV
        echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and tag image
      run: docker build -t ghcr.io/$REPO_NAME:$COMMIT_SHA -f Dockerfile .    

    - name: Push image to GHCR
      run: docker push ghcr.io/$REPO_NAME:$COMMIT_SHA
